import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Blaise",
      email: "admin@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: true,
    },
    {
      name: "Shema",
      email: "user@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free shirt",
      slug: "free-shirt",
      category: "shirts",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "shirts",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim shirt",
      slug: "slim-shirt",
      category: "shirts",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pants",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pants",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pants",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Sport Pants",
      slug: "sport-pants",
      category: "Pants",
      image: "/images/pants4.jpg",
      price: 75,
      brand: "Adidas",
      rating: 4.4,
      numReviews: 9,
      countInStock: 21,
      description: "A popular sport pants",
    },
  ],
}
export default data
