import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Blaise",
      email: "admin@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: true,
    },
    {
      name: "Shema",
      email: "user@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Free shirt",
      slug: "free-shirt",
      category: "Shirt",
      image: "/images/shirt1.jpg",
      price: 70,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Fit Shirt",
      slug: "fit-shirt",
      category: "Shirt",
      image: "/images/shirt2.jpg",
      price: 80,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim shirt",
      slug: "slim-shirt",
      category: "Shirt",
      image: "/images/shirt3.jpg",
      price: 70,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Golf Pants",
      slug: "golf-pants",
      category: "Pant",
      image: "/images/pants1.jpg",
      price: 90,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A smart looking pants",
    },
    {
      name: "Fit Pants",
      slug: "fit-pants",
      category: "Pant",
      image: "/images/pants2.jpg",
      price: 95,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Classic Pants",
      slug: "classic-pants",
      category: "Pant",
      image: "/images/pants3.jpg",
      price: 75,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Sport Pants",
      slug: "sport-pants",
      category: "Pant",
      image: "/images/pants4.jpg",
      price: 75,
      brand: "Adidas",
      rating: 4.4,
      numReviews: 9,
      countInStock: 21,
      description: "A popular sport pants",
    },
    {
      name: "Posh Pants",
      slug: "posh-pants",
      category: "Pant",
      image: "/images/pants5.jpg",
      price: 16,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 10,
      countInStock: 21,
      description: "A popular classic pants",
    },
    {
      name: "Motocross Sport Pants",
      slug: "motocross-pants",
      category: "Pant",
      image: "/images/pants6.jpg",
      price: 20,
      brand: "Ferrari",
      rating: 4.9,
      numReviews: 13,
      countInStock: 11,
      description: "A popular motocross pants lorem",
    },
    {
      name: "Miami Shirt",
      slug: "miami-shirt",
      category: "Shirt",
      image: "/images/shirt4.jpg",
      price: 9,
      brand: "I&M",
      rating: 4.1,
      numReviews: 30,
      countInStock: 41,
      description: "A popular miami shirt",
    },
    {
      name: "Air Jordan",
      slug: "air-jordan",
      category: "Shoes",
      image: "/images/air_jordan.jpg",
      price: 15,
      brand: "Jordan",
      rating: 3.3,
      numReviews: 11,
      countInStock: 20,
      description: "A yellow black jordan made in vietnam orginal",
    },
    {
      name: "Air Jordan 4",
      slug: "air_jordan4_cyan",
      category: "Shoes",
      image: "/images/air_jordan4_cyan.jpg",
      price: 12,
      brand: "Jordan",
      rating: 4.3,
      numReviews: 11,
      countInStock: 30,
      description: "A popular cyan jordan made in vietnam",
    },
    {
      name: "Pink Air jordan 4",
      slug: "air_jordan4_pink",
      category: "Shoes",
      image: "/images/air_jordan4_pink.jpg",
      price: 11,
      brand: "Jordan",
      rating: 2.3,
      numReviews: 6,
      countInStock: 9,
      description: "A popular air jordan 4 made in vietnam",
    },
    {
      name: "White Air Force",
      slug: "air_force_greenwhite",
      category: "Shoes",
      image: "/images/airforce_greenwhite.jpg",
      price: 10,
      brand: "Jordan",
      rating: 1.3,
      numReviews: 15,
      countInStock: 8,
      description:
        "A brand new aiforce shoes with white and green color made in vietnam",
    },
    {
      name: "Black Dior Home Shoes",
      slug: "black_dior_home",
      category: "Shoes",
      image: "/images/diorhome_black.jpg",
      price: 14,
      brand: "Dior",
      rating: 4.3,
      numReviews: 4,
      countInStock: 5,
      description:
        "A brand new dior home shoes with black color made in vietnam",
    },
    {
      name: "White Air Jordan 3",
      slug: "white_air_jordan3",
      category: "Shoes",
      image: "/images/jordan3_white.jpg",
      price: 8,
      brand: "Jordan",
      rating: 3.3,
      numReviews: 14,
      countInStock: 20,
      description:
        "A brand new air jordan 3 shoes with white color made in vietnam",
    },
    {
      name: "White Maqueen",
      slug: "white_maqueen_smallblack",
      category: "Shoes",
      image: "/images/maqueen_white.jpg",
      price: 10,
      brand: "Unknown",
      rating: 5.3,
      numReviews: 11,
      countInStock: 7,
      description: "A brand new maqueen shoes with white color made in vietnam",
    },
  ],
}
export default data
