import bcrypt from "bcryptjs"

const data = {
  users: [
    {
      name: "Blaise",
      email: "admin@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: true,
    },
    {
      name: "Shema",
      email: "user@example.com",
      password: bcrypt.hashSync("ab12345"),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: "Dior T-Shirt",
      category: "Shirt",
      image: "/images/shirt1.jpg",
      price: 9000,
      brand: "Nike",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "A black red cowboy pant",
      category: "Pant",
      image: "/images/pants1.jpg",
      price: 15000,
      brand: "Oliver",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A smart looking black cowboy pant",
    },
    {
      name: "A Blue Fit Pant",
      category: "Pant",
      image: "/images/pants2.jpg",
      price: 12000,
      brand: "Zara",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "A Good Classic Pant",
      category: "Pant",
      image: "/images/pants3.jpg",
      price: 12000,
      brand: "Casely",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular pants",
    },
    {
      name: "Cool Cowboy Pants",
      category: "Pant",
      image: "/images/pants4.jpg",
      price: 14000,
      brand: "Adidas",
      rating: 4.4,
      numReviews: 9,
      countInStock: 21,
      description: "A popular cowboy pants",
    },
    {
      name: "Cool T Shirt",
      category: "Shirt",
      image: "/images/shirt4.jpg",
      price: 9,
      brand: "I&M",
      rating: 4.1,
      numReviews: 30,
      countInStock: 41,
      description: "A popular miami shirt",
    },
    {
      name: "Yellow Air Jordan",
      category: "Shoes",
      image: "/images/air_jordan.jpg",
      price: 30000,
      brand: "Jordan",
      rating: 3.3,
      numReviews: 11,
      countInStock: 20,
      description: "A yellow black jordan made in vietnam orginal",
    },
    {
      name: "Air Jordan 4",
      category: "Shoes",
      image: "/images/air_jordan4_cyan.jpg",
      price: 30000,
      brand: "Jordan",
      rating: 4.3,
      numReviews: 11,
      countInStock: 30,
      description: "A popular cyan jordan made in vietnam",
    },
    {
      name: "White Air Force",
      category: "Shoes",
      image: "/images/airforce_greenwhite.jpg",
      price: 20000,
      brand: "Jordan",
      rating: 1.3,
      numReviews: 15,
      countInStock: 8,
      description:
        "A brand new aiforce shoes with white and green color made in vietnam",
    },
    {
      name: "White Air Jordan",
      category: "Shoes",
      image: "/images/jordan3_white.jpg",
      price: 29000,
      brand: "Jordan",
      rating: 3.3,
      numReviews: 14,
      countInStock: 20,
      description:
        "A brand new air jordan 3 shoes with white color made in vietnam",
    },
    {
      name: "Black Dior Home Shoes",
      category: "Shoes",
      image: "/images/diorhome_black.jpg",
      price: 30000,
      brand: "Dior",
      rating: 4.3,
      numReviews: 4,
      countInStock: 5,
      description:
        "A brand new dior home shoes with black color made in vietnam",
    },
    {
      name: "White Maqueen",
      category: "Shoes",
      image: "/images/maqueen_white.jpg",
      price: 25000,
      brand: "Unknown",
      rating: 5.3,
      numReviews: 11,
      countInStock: 7,
      description: "A brand new maqueen shoes with white color made in vietnam",
    },
    {
      name: "Pink Air jordan 4",
      category: "Shoes",
      image: "/images/air_jordan4_pink.jpg",
      price: 30000,
      brand: "Jordan",
      rating: 2.3,
      numReviews: 6,
      countInStock: 9,
      description: "A popular air jordan 4 made in vietnam",
    },
    {
      name: "Fit Shirt",
      category: "Shirt",
      image: "/images/shirt2.jpg",
      price: 8000,
      brand: "Nike",
      rating: 4.2,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Slim shirt",
      category: "Shirt",
      image: "/images/shirt3.jpg",
      price: 8000,
      brand: "Raymond",
      rating: 4.5,
      numReviews: 10,
      countInStock: 20,
      description: "A popular shirt",
    },
    {
      name: "Christian dior",
      category: "Pant",
      image: "/images/pants5.jpg",
      price: 15000,
      brand: "Adidas",
      rating: 4.3,
      numReviews: 10,
      countInStock: 21,
      description: "A popular classic dior pant",
    },
    {
      name: "Cross popular pant",
      category: "Pant",
      image: "/images/pants6.jpg",
      price: 14000,
      brand: "Ferrari",
      rating: 4.9,
      numReviews: 13,
      countInStock: 11,
      description: "A popular motocross pants lorem",
    },
  ],
}
export default data
